### ISSUE TITLE
Use Radians 

### ISSUE THREAD

**Issue by Fixit-Davide** [roncapat/ROS2-HAL-AdvancedNavigation-Spatial-GNSS#1]
The message NavSatFix wants degress but the node generates Radians. Add a conversion in the code.

**Comment by roncapat** [comment]
Closed by [fff25ac](https://github.com/roncapat/ROS2-HAL-AdvancedNavigation-Spatial-GNSS/commit/fff25ac080a80f0995847d1efdbc56450a1cc4ff)
